/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedContributionsRouteImport } from './routes/_authed/contributions'
import { Route as AuthedContributionsNewRouteImport } from './routes/_authed/contributions.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContributionsRoute = AuthedContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContributionsNewRoute = AuthedContributionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedContributionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contributions': typeof AuthedContributionsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/members': typeof AuthedMembersRoute
  '/profile': typeof AuthedProfileRoute
  '/contributions/new': typeof AuthedContributionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contributions': typeof AuthedContributionsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/members': typeof AuthedMembersRoute
  '/profile': typeof AuthedProfileRoute
  '/contributions/new': typeof AuthedContributionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/contributions': typeof AuthedContributionsRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/contributions/new': typeof AuthedContributionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contributions'
    | '/dashboard'
    | '/members'
    | '/profile'
    | '/contributions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contributions'
    | '/dashboard'
    | '/members'
    | '/profile'
    | '/contributions/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/contributions'
    | '/_authed/dashboard'
    | '/_authed/members'
    | '/_authed/profile'
    | '/_authed/contributions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contributions': {
      id: '/_authed/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AuthedContributionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contributions/new': {
      id: '/_authed/contributions/new'
      path: '/new'
      fullPath: '/contributions/new'
      preLoaderRoute: typeof AuthedContributionsNewRouteImport
      parentRoute: typeof AuthedContributionsRoute
    }
  }
}

interface AuthedContributionsRouteChildren {
  AuthedContributionsNewRoute: typeof AuthedContributionsNewRoute
}

const AuthedContributionsRouteChildren: AuthedContributionsRouteChildren = {
  AuthedContributionsNewRoute: AuthedContributionsNewRoute,
}

const AuthedContributionsRouteWithChildren =
  AuthedContributionsRoute._addFileChildren(AuthedContributionsRouteChildren)

interface AuthedRouteChildren {
  AuthedContributionsRoute: typeof AuthedContributionsRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedContributionsRoute: AuthedContributionsRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedProfileRoute: AuthedProfileRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
